# Generated by Django 5.1.4 on 2025-01-04 02:46

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_alter_student_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('institution_type', multiselectfield.db.fields.MultiSelectField(choices=[('publica', 'Pública'), ('privada', 'Privada'), ('subsidiada', 'Subsidiada')], max_length=100, verbose_name='Tipo de Institución')),
                ('education_level', multiselectfield.db.fields.MultiSelectField(choices=[('preescolar', 'Preescolar'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('media_superior', 'Media Superior'), ('superior', 'Superior')], max_length=100, verbose_name='Nivel Educativo')),
                ('education_modality', multiselectfield.db.fields.MultiSelectField(choices=[('escolarizada', 'Escolarizada'), ('no_escolarizada', 'No Escolarizada'), ('mixta', 'Mixta')], max_length=100, verbose_name='Modalidad Educativa')),
                ('shifts', multiselectfield.db.fields.MultiSelectField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('nocturno', 'Nocturno'), ('tiempo_completo', 'Tiempo Completo')], max_length=100, verbose_name='Turnos')),
                ('street', models.CharField(max_length=200, verbose_name='Calle')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('neighborhood', models.CharField(max_length=200, verbose_name='Colonia')),
                ('municipality', models.CharField(max_length=200, verbose_name='Municipio')),
                ('state', models.CharField(max_length=200, verbose_name='Estado')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/', verbose_name='Logotipo')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('students', models.ManyToManyField(blank=True, related_name='schools', to='students.student')),
            ],
            options={
                'verbose_name': 'Escuela',
                'verbose_name_plural': 'Escuelas',
            },
        ),
    ]
