# Generated by Django 5.1.4 on 2025-01-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.CharField(choices=[('AG', 'Aguascalientes'), ('BC', 'Baja California'), ('BS', 'Baja California Sur'), ('CH', 'Chihuahua'), ('CL', 'Colima'), ('CM', 'Campeche'), ('CO', 'Coahuila'), ('CS', 'Chiapas'), ('DF', 'Ciudad de México'), ('DG', 'Durango'), ('GT', 'Guanajuato'), ('GR', 'Guerrero'), ('HG', 'Hidalgo'), ('JA', 'Jalisco'), ('MX', 'Estado de México'), ('MI', 'Michoacán'), ('MO', 'Morelos'), ('NA', 'Nayarit'), ('NL', 'Nuevo León'), ('OA', 'Oaxaca'), ('PU', 'Puebla'), ('QE', 'Querétaro'), ('QR', 'Quintana Roo'), ('SI', 'Sinaloa'), ('SL', 'San Luis Potosí'), ('SO', 'Sonora'), ('TB', 'Tabasco'), ('TL', 'Tlaxcala'), ('TM', 'Tamaulipas'), ('VE', 'Veracruz'), ('YU', 'Yucatán'), ('ZA', 'Zacatecas')], max_length=2, verbose_name='Estado'),
        ),
    ]
