# Generated by Django 5.1.4 on 2025-01-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellido paterno')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido materno')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento (DD/MM/AAAA)')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'No especificado')], max_length=1, verbose_name='Género')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='CURP')),
                ('enrollment_number', models.CharField(max_length=20, unique=True, verbose_name='Número de matrícula')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
        ),
    ]
